version: "3.8"
services:
  nginx:
    build: requirements/nginx/
    ports:
     - "443:443"
    networks:
      - my-network
    volumes:
      - wp-data:/var/www/
    depends_on:
      - wordpress
      - mariadb
    restart: on-failure

  wordpress:
    build: requirements/wordpress/
    networks:
      - my-network
    volumes:
      - wp-data:/var/www/
    depends_on:
      - mariadb
    restart: on-failure
    env_file:
      - .env

  mariadb:
    build:
      context: requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network
    restart: on-failure
    env_file:
      - .env

volumes:
  wp-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wp

  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/db

networks:
  my-network:
    driver: bridge
    name: network
